export interface TagCategory {
  key: string
  label: string
  fields: TagDef[]
}

export interface TagDef {
  key: string
  label: string
  type: "text" | "number" | "date" | "select"
  options?: string[]
}

const orientations = [
  "1-正常", "2-水平翻转", "3-旋转180°",
  "4-垂直翻转", "5-旋转90°+水平翻转", "6-顺时针90°",
  "7-旋转90°+垂直翻转", "8-逆时针90°",
]

const basicInfo: TagCategory = {
  key: "basic",
  label: "基本信息",
  fields: [
    { key: "ImageDescription", label: "图像描述", type: "text" },
    { key: "DocumentName", label: "文档名称", type: "text" },
    { key: "Make", label: "相机厂商", type: "text" },
    { key: "Model", label: "相机型号", type: "text" },
    { key: "Software", label: "软件", type: "text" },
    { key: "ProcessingSoftware", label: "处理软件", type: "text" },
    { key: "HostComputer", label: "计算机", type: "text" },
    { key: "DateTime", label: "修改时间", type: "date" },
    { key: "DateTimeOriginal", label: "拍摄时间", type: "date" },
    { key: "DateTimeDigitized", label: "数字化时间", type: "date" },
    { key: "SubSecTime", label: "亚秒时间", type: "text" },
    { key: "SubSecTimeOriginal", label: "原始亚秒时间", type: "text" },
    { key: "SubSecTimeDigitized", label: "数字化亚秒时间", type: "text" },
    { key: "ExifVersion", label: "EXIF 版本", type: "text" },
    { key: "FlashpixVersion", label: "FlashPix 版本", type: "text" },
    { key: "Orientation", label: "方向", type: "select", options: orientations },
    { key: "ImageUniqueID", label: "图像唯一 ID", type: "text" },
    { key: "XPSubject", label: "主题", type: "text" },
    { key: "XPTitle", label: "标题", type: "text" },
    { key: "XPKeywords", label: "关键词", type: "text" },
    { key: "XPComment", label: "备注", type: "text" },
    { key: "XPAuthor", label: "作者", type: "text" },
    { key: "Rating", label: "评级", type: "number" },
    { key: "RatingPercent", label: "评级百分比", type: "number" },
  ],
}

const shootingParams: TagCategory = {
  key: "shooting",
  label: "拍摄参数",
  fields: [
    { key: "ExposureTime", label: "快门速度", type: "text" },
    { key: "FNumber", label: "光圈值", type: "number" },
    { key: "ISOSpeedRatings", label: "ISO 感光度", type: "number" },
    { key: "ISOSpeed", label: "ISO 速度", type: "number" },
    { key: "StandardOutputSensitivity", label: "标准输出灵敏度", type: "number" },
    { key: "RecommendedExposureIndex", label: "推荐曝光指数", type: "number" },
    { key: "SensitivityType", label: "灵敏度类型", type: "text" },
    { key: "ISOSpeedLatitudeyyy", label: "ISO 宽容度 YYY", type: "number" },
    { key: "ISOSpeedLatitudezzz", label: "ISO 宽容度 ZZZ", type: "number" },
    { key: "ExposureProgram", label: "曝光程序", type: "select", options: ["0-未定义", "1-手动", "2-程序自动", "3-光圈优先", "4-快门优先", "5-创意(慢速)", "6-动作(高速)", "7-肖像", "8-风景"] },
    { key: "ExposureMode", label: "曝光模式", type: "select", options: ["0-自动", "1-手动", "2-自动包围"] },
    { key: "ExposureBiasValue", label: "曝光补偿", type: "number" },
    { key: "ShutterSpeedValue", label: "快门速度值", type: "number" },
    { key: "ApertureValue", label: "光圈值", type: "number" },
    { key: "BrightnessValue", label: "亮度值", type: "number" },
    { key: "MaxApertureValue", label: "最大光圈值", type: "number" },
    { key: "MeteringMode", label: "测光模式", type: "select", options: ["0-未知", "1-平均", "2-中央重点", "3-点测光", "4-多区", "5-多点", "6-部分"] },
    { key: "LightSource", label: "光源", type: "text" },
    { key: "Flash", label: "闪光灯", type: "select", options: ["0-未闪光", "1-闪光", "5-闪光(反射检测)", "16-未闪光(强制)", "24-自动未闪光", "25-自动闪光", "32-无闪光功能", "65-闪光(红眼)", "73-闪光(红眼+反射检测)"] },
    { key: "FlashEnergy", label: "闪光能量", type: "number" },
    { key: "FocalLength", label: "焦距(mm)", type: "number" },
    { key: "FocalLengthIn35mmFilm", label: "35mm 等效焦距(mm)", type: "number" },
    { key: "DigitalZoomRatio", label: "数码变焦倍率", type: "number" },
    { key: "SubjectDistance", label: "拍摄距离(m)", type: "number" },
    { key: "SubjectDistanceRange", label: "拍摄距离范围", type: "select", options: ["0-未知", "1-微距", "2-近距离", "3-远距离"] },
    { key: "SubjectArea", label: "主体区域", type: "text" },
    { key: "SubjectLocation", label: "主体位置", type: "text" },
    { key: "WhiteBalance", label: "白平衡", type: "select", options: ["0-自动", "1-手动"] },
    { key: "CustomRendered", label: "自定义渲染", type: "select", options: ["0-正常", "1-自定义"] },
    { key: "SceneCaptureType", label: "场景类型", type: "select", options: ["0-标准", "1-风景", "2-肖像", "3-夜景"] },
    { key: "SceneType", label: "场景类型(详细)", type: "text" },
    { key: "GainControl", label: "增益控制", type: "select", options: ["0-无", "1-低增益提升", "2-高增益提升", "3-低增益降低", "4-高增益降低"] },
    { key: "Contrast", label: "对比度", type: "select", options: ["0-正常", "1-柔和", "2-强烈"] },
    { key: "Saturation", label: "饱和度", type: "select", options: ["0-正常", "1-低饱和度", "2-高饱和度"] },
    { key: "Sharpness", label: "锐度", type: "select", options: ["0-正常", "1-柔和", "2-强烈"] },
    { key: "FileSource", label: "文件来源", type: "text" },
    { key: "SensingMethod", label: "感光方式", type: "select", options: ["1-单区域彩色", "2-双区域彩色", "3-三区域彩色", "4-色序彩色", "5-线性", "7-三线", "8-色彩顺序线性"] },
    { key: "ColorSpace", label: "色彩空间", type: "select", options: ["1-sRGB", "2-Adobe RGB", "65535-未校准"] },
    { key: "CompressedBitsPerPixel", label: "压缩位/像素", type: "number" },
    { key: "ComponentsConfiguration", label: "分量配置", type: "text" },
    { key: "DeviceSettingDescription", label: "设备设置描述", type: "text" },
    { key: "OECF", label: "光电转换函数", type: "text" },
    { key: "SpectralSensitivity", label: "光谱灵敏度", type: "text" },
    { key: "ExposureIndex", label: "曝光指数", type: "number" },
    { key: "SelfTimerMode", label: "自拍模式", type: "text" },
    { key: "TimeZoneOffset", label: "时区偏移", type: "text" },
  ],
}

const cameraLens: TagCategory = {
  key: "camera",
  label: "相机与镜头",
  fields: [
    { key: "UniqueCameraModel", label: "相机型号(唯一)", type: "text" },
    { key: "LocalizedCameraModel", label: "相机型号(本地化)", type: "text" },
    { key: "CameraSerialNumber", label: "相机序列号", type: "text" },
    { key: "CameraOwnerName", label: "相机所有者", type: "text" },
    { key: "BodySerialNumber", label: "机身序列号", type: "text" },
    { key: "LensMake", label: "镜头厂商", type: "text" },
    { key: "LensModel", label: "镜头型号", type: "text" },
    { key: "LensSpecification", label: "镜头规格", type: "text" },
    { key: "LensSerialNumber", label: "镜头序列号", type: "text" },
    { key: "MakerNote", label: "厂商备注", type: "text" },
    { key: "MakerNoteSafety", label: "厂商备注安全", type: "select", options: ["0-不安全", "1-安全"] },
    { key: "BatteryLevel", label: "电池电量", type: "text" },
  ],
}

const gpsInfo: TagCategory = {
  key: "gps",
  label: "GPS 位置",
  fields: [
    { key: "GPSVersionID", label: "GPS 版本", type: "text" },
    { key: "GPSLatitudeRef", label: "纬度参考", type: "select", options: ["N-北纬", "S-南纬"] },
    { key: "GPSLatitude", label: "纬度", type: "number" },
    { key: "GPSLongitudeRef", label: "经度参考", type: "select", options: ["E-东经", "W-西经"] },
    { key: "GPSLongitude", label: "经度", type: "number" },
    { key: "GPSAltitudeRef", label: "海拔参考", type: "select", options: ["0-海平面", "1-海平面以下"] },
    { key: "GPSAltitude", label: "海拔(米)", type: "number" },
    { key: "GPSTimeStamp", label: "GPS 时间", type: "text" },
    { key: "GPSSatellites", label: "卫星信息", type: "text" },
    { key: "GPSStatus", label: "GPS 状态", type: "text" },
    { key: "GPSMeasureMode", label: "测量模式", type: "text" },
    { key: "GPSDOP", label: "精度因子", type: "number" },
    { key: "GPSSpeedRef", label: "速度参考", type: "text" },
    { key: "GPSSpeed", label: "速度", type: "number" },
    { key: "GPSTrackRef", label: "方向参考", type: "text" },
    { key: "GPSTrack", label: "方向", type: "number" },
    { key: "GPSImgDirectionRef", label: "图像方向参考", type: "text" },
    { key: "GPSImgDirection", label: "图像方向", type: "number" },
    { key: "GPSMapDatum", label: "地图基准", type: "text" },
    { key: "GPSDestLatitudeRef", label: "目标纬度参考", type: "text" },
    { key: "GPSDestLatitude", label: "目标纬度", type: "number" },
    { key: "GPSDestLongitudeRef", label: "目标经度参考", type: "text" },
    { key: "GPSDestLongitude", label: "目标经度", type: "number" },
    { key: "GPSDestBearingRef", label: "目标方位参考", type: "text" },
    { key: "GPSDestBearing", label: "目标方位", type: "number" },
    { key: "GPSDestDistanceRef", label: "目标距离参考", type: "text" },
    { key: "GPSDestDistance", label: "目标距离", type: "number" },
    { key: "GPSProcessingMethod", label: "处理方法", type: "text" },
    { key: "GPSAreaInformation", label: "区域信息", type: "text" },
    { key: "GPSDateStamp", label: "GPS 日期", type: "date" },
    { key: "GPSDifferential", label: "差分修正", type: "number" },
    { key: "GPSHPositioningError", label: "水平定位误差", type: "number" },
  ],
}

const copyright: TagCategory = {
  key: "copyright",
  label: "版权信息",
  fields: [
    { key: "Artist", label: "创作者", type: "text" },
    { key: "Copyright", label: "版权声明", type: "text" },
    { key: "UserComment", label: "用户注释", type: "text" },
    { key: "ImageHistory", label: "图像历史", type: "text" },
    { key: "ImageID", label: "图像 ID", type: "text" },
    { key: "SecurityClassification", label: "安全等级", type: "text" },
  ],
}

const imageProperties: TagCategory = {
  key: "image",
  label: "图像属性",
  fields: [
    { key: "ImageWidth", label: "图像宽度", type: "number" },
    { key: "ImageLength", label: "图像高度", type: "number" },
    { key: "PixelXDimension", label: "像素宽度", type: "number" },
    { key: "PixelYDimension", label: "像素高度", type: "number" },
    { key: "XResolution", label: "水平分辨率", type: "number" },
    { key: "YResolution", label: "垂直分辨率", type: "number" },
    { key: "ResolutionUnit", label: "分辨率单位", type: "select", options: ["1-无单位", "2-英寸", "3-厘米"] },
    { key: "BitsPerSample", label: "位深(Bit)", type: "number" },
    { key: "SamplesPerPixel", label: "每像素采样数", type: "number" },
    { key: "Compression", label: "压缩方式", type: "select", options: ["1-未压缩", "2-CCITT 1D", "3-G3 Group Fax", "4-G4 Group Fax", "5-LZW", "6-JPEG(旧)", "7-JPEG", "8-紧缩", "32946-Deflate"] },
    { key: "PhotometricInterpretation", label: "光度解释", type: "select", options: ["0-白为零", "1-黑为零", "2-RGB", "3-调色板", "4-透明遮罩", "5-CMYK", "6-YCbCr", "8-CIELab"] },
    { key: "PlanarConfiguration", label: "平面配置", type: "select", options: ["1-连续", "2-分平面"] },
    { key: "SampleFormat", label: "采样格式", type: "select", options: ["1-无符号整数", "2-有符号整数", "3-IEEE浮点", "4-未定义"] },
    { key: "SMinSampleValue", label: "最小采样值", type: "text" },
    { key: "SMaxSampleValue", label: "最大采样值", type: "text" },
    { key: "ExtraSamples", label: "额外采样", type: "text" },
    { key: "YCbCrCoefficients", label: "YCbCr 系数", type: "text" },
    { key: "YCbCrSubSampling", label: "YCbCr 子采样", type: "text" },
    { key: "YCbCrPositioning", label: "YCbCr 定位", type: "select", options: ["1-居中", "2-同位置"] },
    { key: "ReferenceBlackWhite", label: "参考黑白点", type: "text" },
    { key: "TransferFunction", label: "传输函数", type: "text" },
    { key: "WhitePoint", label: "白点", type: "text" },
    { key: "PrimaryChromaticities", label: "基色度", type: "text" },
    { key: "ColorMap", label: "颜色映射", type: "text" },
    { key: "Gamma", label: "Gamma 值", type: "number" },
    { key: "NewSubfileType", label: "子文件类型", type: "number" },
    { key: "SubfileType", label: "文件类型", type: "number" },
  ],
}

const dngRawData: TagCategory = {
  key: "dng",
  label: "DNG 原始数据",
  fields: [
    { key: "DNGVersion", label: "DNG 版本", type: "text" },
    { key: "DNGBackwardVersion", label: "DNG 向后兼容版本", type: "text" },
    { key: "ColorMatrix1", label: "色彩矩阵 1", type: "text" },
    { key: "ColorMatrix2", label: "色彩矩阵 2", type: "text" },
    { key: "CameraCalibration1", label: "相机校准 1", type: "text" },
    { key: "CameraCalibration2", label: "相机校准 2", type: "text" },
    { key: "ReductionMatrix1", label: "还原矩阵 1", type: "text" },
    { key: "ReductionMatrix2", label: "还原矩阵 2", type: "text" },
    { key: "AnalogBalance", label: "模拟平衡", type: "text" },
    { key: "AsShotNeutral", label: "拍摄中性点", type: "text" },
    { key: "AsShotWhiteXY", label: "拍摄白点 XY", type: "text" },
    { key: "BaselineExposure", label: "基准曝光", type: "text" },
    { key: "BaselineNoise", label: "基准噪点", type: "text" },
    { key: "BaselineSharpness", label: "基准锐度", type: "text" },
    { key: "BayerGreenSplit", label: "拜耳绿分离", type: "number" },
    { key: "LinearResponseLimit", label: "线性响应限制", type: "number" },
    { key: "ChromaBlurRadius", label: "色差模糊半径", type: "number" },
    { key: "AntiAliasStrength", label: "抗锯齿强度", type: "number" },
    { key: "ShadowScale", label: "阴影比例", type: "text" },
    { key: "DNGPrivateData", label: "DNG 私有数据", type: "text" },
    { key: "CalibrationIlluminant1", label: "校准光源 1", type: "text" },
    { key: "CalibrationIlluminant2", label: "校准光源 2", type: "text" },
    { key: "BestQualityScale", label: "最佳质量比例", type: "text" },
    { key: "RawDataUniqueID", label: "原始数据唯一 ID", type: "text" },
    { key: "OriginalRawFileName", label: "原始 RAW 文件名", type: "text" },
    { key: "OriginalRawFileData", label: "原始 RAW 文件数据", type: "text" },
    { key: "OriginalRawFileDigest", label: "原始 RAW 文件摘要", type: "text" },
    { key: "ActiveArea", label: "有效区域", type: "text" },
    { key: "MaskedAreas", label: "遮罩区域", type: "text" },
    { key: "ColorimetricReference", label: "比色参考", type: "text" },
    { key: "CameraCalibrationSignature", label: "相机校准签名", type: "text" },
    { key: "ProfileCalibrationSignature", label: "配置文件校准签名", type: "text" },
    { key: "AsShotProfileName", label: "拍摄配置文件名称", type: "text" },
    { key: "NoiseReductionApplied", label: "降噪应用", type: "text" },
    { key: "ProfileName", label: "配置文件名称", type: "text" },
    { key: "ProfileHueSatMapDims", label: "配置文件色相饱和度映射维度", type: "text" },
    { key: "ProfileHueSatMapData1", label: "配置文件色相饱和度数据 1", type: "text" },
    { key: "ProfileHueSatMapData2", label: "配置文件色相饱和度数据 2", type: "text" },
    { key: "ProfileToneCurve", label: "配置文件色调曲线", type: "text" },
    { key: "ProfileEmbedPolicy", label: "配置文件嵌入策略", type: "text" },
    { key: "ProfileCopyright", label: "配置文件版权", type: "text" },
    { key: "ProfileLookTableDims", label: "配置文件查找表维度", type: "text" },
    { key: "ProfileLookTableData", label: "配置文件查找表数据", type: "text" },
    { key: "ForwardMatrix1", label: "前向矩阵 1", type: "text" },
    { key: "ForwardMatrix2", label: "前向矩阵 2", type: "text" },
    { key: "PreviewApplicationName", label: "预览应用程序", type: "text" },
    { key: "PreviewApplicationVersion", label: "预览应用版本", type: "text" },
    { key: "PreviewSettingsName", label: "预览设置名称", type: "text" },
    { key: "PreviewSettingsDigest", label: "预览设置摘要", type: "text" },
    { key: "PreviewColorSpace", label: "预览色彩空间", type: "text" },
    { key: "PreviewDateTime", label: "预览日期时间", type: "text" },
    { key: "RawImageDigest", label: "原始图像摘要", type: "text" },
    { key: "OpcodeList1", label: "操作码列表 1", type: "text" },
    { key: "OpcodeList2", label: "操作码列表 2", type: "text" },
    { key: "OpcodeList3", label: "操作码列表 3", type: "text" },
    { key: "NoiseProfile", label: "噪点配置文件", type: "text" },
    { key: "LensInfo", label: "镜头信息", type: "text" },
    { key: "CFAPlaneColor", label: "CFA 平面颜色", type: "text" },
    { key: "CFALayout", label: "CFA 布局", type: "text" },
    { key: "CFAPattern", label: "CFA 模式", type: "text" },
    { key: "CFARepeatPatternDim", label: "CFA 重复模式维度", type: "text" },
    { key: "LinearizationTable", label: "线性化表", type: "text" },
    { key: "BlackLevelRepeatDim", label: "黑电平重复维度", type: "text" },
    { key: "BlackLevel", label: "黑电平", type: "text" },
    { key: "BlackLevelDeltaH", label: "黑电平水平 Delta", type: "text" },
    { key: "BlackLevelDeltaV", label: "黑电平垂直 Delta", type: "text" },
    { key: "WhiteLevel", label: "白电平", type: "text" },
    { key: "DefaultScale", label: "默认比例", type: "text" },
    { key: "DefaultCropOrigin", label: "默认裁剪起点", type: "text" },
    { key: "DefaultCropSize", label: "默认裁剪尺寸", type: "text" },
    { key: "AsShotICCProfile", label: "拍摄 ICC 配置文件", type: "text" },
    { key: "AsShotPreProfileMatrix", label: "拍摄前配置文件矩阵", type: "text" },
    { key: "CurrentICCProfile", label: "当前 ICC 配置文件", type: "text" },
    { key: "CurrentPreProfileMatrix", label: "当前前配置文件矩阵", type: "text" },
    { key: "SubTileBlockSize", label: "子瓦区块大小", type: "text" },
    { key: "RowInterleaveFactor", label: "行交错因子", type: "text" },
  ],
}

const technicalInfo: TagCategory = {
  key: "technical",
  label: "技术信息",
  fields: [
    { key: "Threshholding", label: "阈值", type: "text" },
    { key: "CellWidth", label: "单元格宽度", type: "number" },
    { key: "CellLength", label: "单元格高度", type: "number" },
    { key: "FillOrder", label: "填充顺序", type: "text" },
    { key: "StripOffsets", label: "条带偏移", type: "text" },
    { key: "RowsPerStrip", label: "每条带行数", type: "number" },
    { key: "StripByteCounts", label: "条带字节数", type: "text" },
    { key: "GrayResponseUnit", label: "灰度响应单位", type: "text" },
    { key: "GrayResponseCurve", label: "灰度响应曲线", type: "text" },
    { key: "T4Options", label: "T4 选项", type: "text" },
    { key: "T6Options", label: "T6 选项", type: "text" },
    { key: "Predictor", label: "预测器", type: "text" },
    { key: "HalftoneHints", label: "半色调提示", type: "text" },
    { key: "TileWidth", label: "瓦片宽度", type: "number" },
    { key: "TileLength", label: "瓦片高度", type: "number" },
    { key: "TileOffsets", label: "瓦片偏移", type: "text" },
    { key: "TileByteCounts", label: "瓦片字节数", type: "text" },
    { key: "SubIFDs", label: "子 IFD", type: "text" },
    { key: "InkSet", label: "墨水集合", type: "text" },
    { key: "InkNames", label: "墨水名称", type: "text" },
    { key: "NumberOfInks", label: "墨水数量", type: "number" },
    { key: "DotRange", label: "网点范围", type: "text" },
    { key: "TargetPrinter", label: "目标打印机", type: "text" },
    { key: "ClipPath", label: "裁剪路径", type: "text" },
    { key: "XClipPathUnits", label: "X 裁剪路径单位", type: "text" },
    { key: "YClipPathUnits", label: "Y 裁剪路径单位", type: "text" },
    { key: "Indexed", label: "索引模式", type: "text" },
    { key: "JPEGTables", label: "JPEG 表", type: "text" },
    { key: "JPEGProc", label: "JPEG 处理", type: "text" },
    { key: "JPEGInterchangeFormat", label: "JPEG 交换格式", type: "text" },
    { key: "JPEGInterchangeFormatLength", label: "JPEG 交换格式长度", type: "text" },
    { key: "JPEGRestartInterval", label: "JPEG 重启间隔", type: "number" },
    { key: "JPEGLosslessPredictors", label: "JPEG 无损预测器", type: "text" },
    { key: "JPEGPointTransforms", label: "JPEG 点变换", type: "text" },
    { key: "JPEGQTables", label: "JPEG 量化表", type: "text" },
    { key: "JPEGDCTables", label: "JPEG DC 表", type: "text" },
    { key: "JPEGACTables", label: "JPEG AC 表", type: "text" },
    { key: "OPIProxy", label: "OPI 代理", type: "text" },
    { key: "XMLPacket", label: "XML 数据包", type: "text" },
    { key: "ImageResources", label: "图像资源", type: "text" },
    { key: "ExifTag", label: "EXIF 标签指针", type: "text" },
    { key: "InterColorProfile", label: "ICC 色彩配置文件", type: "text" },
    { key: "GPSTag", label: "GPS 标签指针", type: "text" },
    { key: "Interlace", label: "隔行扫描", type: "text" },
    { key: "InteroperabilityTag", label: "互操作性标签", type: "text" },
    { key: "RelatedSoundFile", label: "相关音频文件", type: "text" },
    { key: "PrintImageMatching", label: "打印图像匹配", type: "text" },
    { key: "FocalPlaneXResolution", label: "焦平面水平分辨率", type: "text" },
    { key: "FocalPlaneYResolution", label: "焦平面垂直分辨率", type: "text" },
    { key: "FocalPlaneResolutionUnit", label: "焦平面分辨率单位", type: "text" },
    { key: "SpatialFrequencyResponse", label: "空间频率响应", type: "text" },
    { key: "Noise", label: "噪点", type: "text" },
    { key: "TransferRange", label: "传输范围", type: "text" },
    { key: "ImageNumber", label: "图像编号", type: "number" },
    { key: "TIFFEPStandardID", label: "TIFF-EP 标准 ID", type: "text" },
  ],
}

export const tagCategories: TagCategory[] = [
  basicInfo,
  shootingParams,
  cameraLens,
  gpsInfo,
  copyright,
  imageProperties,
  dngRawData,
  technicalInfo,
]

export function getTagDef(key: string): TagDef | undefined {
  for (const cat of tagCategories) {
    for (const field of cat.fields) {
      if (field.key === key) return field
    }
  }
}
